// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gibbs_sampling_iter
NumericVector gibbs_sampling_iter(const NumericVector& last_sample, const NumericMatrix& sigma, const NumericVector& mu);
RcppExport SEXP _SA23229024_gibbs_sampling_iter(SEXP last_sampleSEXP, SEXP sigmaSEXP, SEXP muSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type last_sample(last_sampleSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type mu(muSEXP);
    rcpp_result_gen = Rcpp::wrap(gibbs_sampling_iter(last_sample, sigma, mu));
    return rcpp_result_gen;
END_RCPP
}
// Gibbs_sampling_cpp
NumericMatrix Gibbs_sampling_cpp(int N, int burnin, NumericMatrix sigma, NumericVector mu);
RcppExport SEXP _SA23229024_Gibbs_sampling_cpp(SEXP NSEXP, SEXP burninSEXP, SEXP sigmaSEXP, SEXP muSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    rcpp_result_gen = Rcpp::wrap(Gibbs_sampling_cpp(N, burnin, sigma, mu));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SA23229024_gibbs_sampling_iter", (DL_FUNC) &_SA23229024_gibbs_sampling_iter, 3},
    {"_SA23229024_Gibbs_sampling_cpp", (DL_FUNC) &_SA23229024_Gibbs_sampling_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_SA23229024(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
