# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Gibbs sampling iteration
#' @name gibbs_sampling
#' @description Perform one iteration of Gibbs sampling
#' @param last_sample A numeric vector representing the last sample
#' @param sigma Covariance matrix for the bivariate normal distribution
#' @param mu Mean vector for the bivariate normal distribution
#' @return A numeric vector representing the new sample
#' @export
gibbs_sampling_iter <- function(last_sample, sigma, mu) {
    .Call('_SA23229024_gibbs_sampling_iter', PACKAGE = 'SA23229024', last_sample, sigma, mu)
}

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param N Total number of samples to generate
#' @param burnin Number of initial samples to discard
#' @param sigma Covariance matrix for the bivariate normal distribution
#' @param mu Mean vector for the bivariate normal distribution
#' @return A numeric matrix with each row being a sample from the distribution
#' @examples
#' \dontrun{
#' # Define the mean vector and covariance matrix for a bivariate normal distribution
#' mu <- c(0, 0)
#' sigma <- matrix(c(1, 0.5, 0.5, 1), nrow = 2, byrow = TRUE)
#' # Run Gibbs sampling to generate samples
#' set.seed(123) # Set seed for reproducibility
#' samples <- Gibbs_sampling_cpp(N = 1000, burnin = 100, sigma = sigma, mu = mu)
#' }
#' @export
Gibbs_sampling_cpp <- function(N, burnin, sigma, mu) {
    .Call('_SA23229024_Gibbs_sampling_cpp', PACKAGE = 'SA23229024', N, burnin, sigma, mu)
}

